# Generated by Django 2.2.7 on 2019-11-28 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='id_auth',
        ),
    ]
