# Generated by Django 2.2.7 on 2019-11-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20191128_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='gamecrush.User'),
        ),
    ]
