# Generated by Django 2.2.7 on 2019-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamecrush', '0003_auto_20191127_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
